Repository huijari/silver-train, pull requests merged in 2022-05, with the labels that each got.

#21 Add option to import Firefox accounts
  package-lock.json
  package.json
  src/index.ts
Labels: feature

#26 Fix iv reuse
  src/index.ts
Labels: bug

#30 Implement password generation
  package-lock.json
  package.json
  src/index.ts
Labels: feature

#35 Refactoring init
  src/crypto.ts
  src/index.ts
  src/signInOrSignUp.ts
Labels: refactor

#36 extract encrypt and decrypt functions
  src/account.ts
  src/crypto.ts
  src/menu/changeMasterPassword.ts
Labels: refactor
